### ISSUE TITLE
Contact info

### ISSUE THREAD

**Issue by Michael21107** [Rich-Dunne/SchedulingApp#1]
Hey Rich. Sorry for writing you here but lcpdfr.com runs un-useably slow when I'm logged in. Please, is there a way to contact you outside of lcpdfr.com? I'd be okay with the issues of this repo if needed.

**Comment by Rich-Dunne** [comment]
Hi Michael,

No, it is not okay to make issues on random repos for your LSPDFR issues.  I'm going to close this issue and hope you never do this again.
